import turtle
import random
screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('pink')
t=turtle.Turtle()
t.speed(0)

#intro screen
t.penup()
t.goto(0,100)
t.pendown()
t.write("Anna's awesome life",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(0,60)
t.pendown()
t.write("By: Anna",font=("Arial",20,"bold"),align="center")

t.penup()
t.goto(-150,-100)
t.pendown()
screen.addshape('flower.gif')
t.shape('flower.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(150,-100)
t.pendown()
screen.addshape('sunset1.gif')
t.shape('sunset1.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(240,280)
t.pendown()

t.fillcolor("hotpink1")
t.begin_fill()
t.setheading(135)
t.forward(100)
t.setheading(225)
t.forward(100)
t.setheading(315)
t.forward(100)
t.setheading(45)
t.forward(100)
t.end_fill()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("Press enter to continue!",font=("Arial",30,"bold"),align="center")

#next slide
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor('lightblue')

t.penup()
t.goto(0,150)
t.pendown()
t.write("My favorite foods",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(150,-100)
t.pendown()
screen.addshape('ss.gif')
t.shape('ss.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(150,-280)
t.pendown()
t.write("Sushi!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(-150,-100)
t.pendown()
screen.addshape('mac.gif')
t.shape('mac.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(-150,-280)
t.pendown()
t.write("Mac n cheese!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(0,70)
t.pendown()
t.write("I like pizza",font=("Arial",30,"bold"),align="center")

t.fillcolor("blue")
t.begin_fill()
t.penup()
t.goto(-200,275)
t.pendown()
t.pencolor('blue')
t.circle(45)
t.end_fill()

#next slide
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor('lightyellow')
t.pencolor('black')
t.penup()
t.goto(0,150)
t.pendown()
t.write("My hobbies!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(-150,-100)
t.pendown()
screen.addshape('camp.gif')
t.shape('camp.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(-150,-280)
t.pendown()
t.write("Camping!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(150,-100)
t.pendown()
screen.addshape('hike.gif')
t.shape('hike.gif')
t.stamp()
t.shape("classic")

t.penup()
t.goto(150,-280)
t.pendown()
t.write("Hiking!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(0,70)
t.pendown()
t.write("I like to swim and watch movies",font=("Arial",30,"bold"),align="center")

t.penup()
t.fillcolor('yellow')
t.begin_fill()
t.goto(100,200)
t.pendown()
t.goto(150,300)
t.goto(200,300)
t.goto(250,200)
t.goto(100,200)
t.end_fill()

#next slide
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor('lightgreen')
t.pencolor('black')
t.penup()
t.goto(0,150)
t.pendown()
t.write("My favorite movie!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(-150,-100)
t.pendown()
screen.addshape('noah.gif')
t.shape('noah.gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(150,-100)
t.write("The Notebook!",font=("Arial",30,"bold"),align="center")

t.penup()
t.fillcolor("darkgreen")
t.begin_fill()
t.goto(-300,300)
t.pendown()
t.setheading
t.forward(100)
t.right(90)
t.forward(40)
t.right(90)
t.forward(100)
t.right(90)
t.forward(40)
t.right(90)
t.end_fill()
t.penup()

t.penup()
t.goto(0,-300)
t.pendown()
t.write("Press enter to continue!",font=("Arial",30,"bold"),align="center")

#nextslide
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor('lavender')
t.pencolor('black')
t.penup()
t.goto(0,150)
t.pendown()
t.write("My favorite sport!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(-150,-100)
t.pendown()
screen.addshape('color.gif')
t.shape('color.gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(150,-100)
t.write("Color guard!",font=("Arial",30,"bold"),align="center")

t.penup()
t.goto(225,-280)
t.fillcolor('purple')
t.begin_fill()
t.pendown()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()



turtle.done()